### ISSUE TITLE
Dear Author

### ISSUE THREAD

**Issue by DonghoonPark12** [WangXFng/EEDN#1]
Thanks for great work.
Can you send me paper pdf? Cause I don't have account of ACM.

email: donghunp1212@gmail.com

If you send me, I'll really appreciate.

**Comment by WangXFng** [comment]
Would you please check the folder named "/paper" in this repository? I have put the pdf file there.
If you cannot find it, I will send it through email.

**Comment by DonghoonPark12** [comment]
Thank a alot :)
