### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by L-JuneF** [WangXFng/EEDN#2]
请问如果我想运行其他数据集的话，tune.txt文件如何获取？

**Comment by WangXFng** [comment]
如果你的方法和所有baseline的都只用了训练集和测试集的话，比如8:2。你只要保证测试集是一致的就是公平的比较，比如把训练集再细划分为7:1作为train.txt和tune.txt。如果是涉及到序列特征之类的，划分的时候最好保证一下前后顺序。

**Comment by L-JuneF** [comment]
哇，回复好快！感谢，就是说把训练集分10%作为tune就行了吧

**Comment by WangXFng** [comment]
是的。祝你科研顺利！

**Comment by L-JuneF** [comment]
> 是的。祝你科研顺利！

感谢，你也是
